name: mesmerize
base: core18
version: 0.1.0
grade: stable
summary: Platform for Calcium Imaging analysis
description: >
  Calcium imaging anlaysis platform

confinement: strict


parts:
#  setup:
    # Should try including desktop-gtk3 at some time to see if it fixes warnings on Fedora?
#    after: [desktop-qt5]
#    plugin: python
#    python-version: python3
#    source: .
#    source-type: git
#    source-branch: snap
    # Cython is required for setup.py, python-dateutils is required by pandas and for whatever reason doesn't get installed automatically
#    python-packages: [Cython, python-dateutil, numpy]
#    build-packages:
#      - tcl
#      - python3
#      - python3-tk
#      - python3-pyqt5
#      - gcc
#      - g++
#      - libatlas-base-dev
#      - gfortran
#      - libblas3
#      - liblapack3
#      - libopenblas-dev
#      - liblapack-dev
#      - libblas-dev
#      - cython3
#      - graphviz
#      - qtbase5-dev
#      - libqt5gui5
#      - libqt5svg5
#    stage-packages:
#      - libatlas-base-dev
  mesmerize:
    after: [desktop-qt5]
    plugin: python
    requirements: requirements.txt
    python-packages: [Cython, python-dateutil, numpy]
    python-version: python3
    source: .
#    source-type: git
    source-branch: snap
    build-packages:
      - tcl
      - python3
      - python3-tk
      - python3-pyqt5
      - gcc
      - g++
      - libatlas-base-dev
      - gfortran
      - libblas3
      - liblapack3
      - libopenblas-dev
      - liblapack-dev
      - libblas-dev
      - cython3
      - graphviz
    stage-packages:
      - gcc
      - g++
      - libatlas-base-dev
      - gfortran
      - libblas3
      - liblapack3
      - libopenblas-dev
      - liblapack-dev
      - libblas-dev
      - tcl
      - python3
      - python3-tk
      - python3-pyqt5
      - libc-bin
      - locales
      - cython3
      - qtwayland5
      - graphviz
#      - libagg-dev
#      - libcairo2
#      - libcairo2-dev
#      - libgs9
#      - libgs9-common
#      - libgs-dev
#      - libpng16-16
#      - libpng-dev
#      - libfontconfig1
#      - libfontconfig1-dev
#      - zlibc
#      - evince
#      - libqt5gui5
#      - libqt5svg5
#      - qtbase5-dev
  # From https://github.com/dmnfarrell/pandastable/blob/master/snap/snapcraft.yaml
  filesets: #to deal with problem finding init.tcl
    plugin: dump
    source: /usr/share/tcltk/
    organize:
         '*': ./usr/lib/

apps:
  mesmerize:
    command: desktop-launch $SNAP/bin/mesmerize
    environment:
        # To work on Fedora
        DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - opengl
      - home
      - network
      - network-bind
      - removable-media
  mesmerize-ipython:
    command: bin/ipython3
    environment:
        # To work on Fedora
        DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - opengl
      - home
      - network
      - network-bind
      - removable-media

